name: card_game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: DragonHunter
      fonts:
        - asset: assets/fonts/DragonHunter.otf
  assets:
    - assets/images/Backgrounds/Home_Screen_Background.png 
    - assets/images/Backgrounds/Home_Screen_Background2.png
    - assets/images/Backgrounds/dnd-abandoned-house.jpg
    - assets/images/Backgrounds/dnd-workspace.jpg
    - assets/images/Backgrounds/Backside1.png
    - assets/images/Backgrounds/
    - assets/images/
    - images/Backgrounds/Menu1.png
    - images/Backgrounds/Menu2.png
    - images/Backgrounds/Home_Screen_Background.png
